---
apiVersion: v1
kind: Pod
metadata:
  name: xcr
  labels:
    app: tools
spec:
  hostNetwork: true
  containers:
    - name: tools-container
      image: xcr9/xcr9
      command:
        - /bin/bash
        - -c
        - tail -f /dev/null
