apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: kube-logging
data:
  fluent.conf: |
    <source>
      @type tail
      path /var/log/containers/*.log
      pos_file /var/log/fluentd-containers.log.pos
      tag kube.*
      format json
      read_from_head true
      encoding utf-8
    </source>

    <filter kube.**>
      @type parser
      format json
      key_name log
      reserve_data true
    </filter>

    <match kube.**>
      @type forward
      <server>
        host logstash-service.kube-logging.svc.cluster.local
        port 5044
      </server>
    </match>

    <system>
      log_level error
    </system>
