apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  namespace: kube-logging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
        - name: logstash
          image: docker.elastic.co/logstash/logstash:8.10.0
          env:
            - name: LS_JAVA_OPTS
              value: "-Xms1g -Xmx2g"  # Set minimum (Xms) and maximum (Xmx) heap size
          ports:
            - containerPort: 5044
          volumeMounts:
            - name: config-volume
              mountPath: /usr/share/logstash/pipeline
              readOnly: true
      volumes:
        - name: config-volume
          configMap:
            name: logstash-config

