apiVersion: v1
kind: ConfigMap
metadata:
  name: cassandra-setup-config
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.app.labels.app }}
    version: {{ .Values.app.labels.version }}
