apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.statefulset.serviceName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.app.labels.app }}
    version: {{ .Values.app.labels.version }}
spec:
  clusterIP: None
  selector:
    app: {{ .Values.app.labels.app }}
  ports:
    - name: cql
      port: 9042
    - name: intra-node
      port: 7000
    - name: intra-node-tls
      port: 7001
    - name: jmx
      port: 7199
