apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.app.labels.app }}
    version: {{ .Values.app.labels.version }}
spec:
  serviceName: {{ .Values.statefulset.serviceName }}
  replicas: {{ .Values.statefulset.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app.labels.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.labels.app }}
        version: {{ .Values.app.labels.version }}
    spec:
      terminationGracePeriodSeconds:
        {{ .Values.statefulset.terminationGracePeriod }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - {{ .Values.app.labels.app }}
                topologyKey: kubernetes.io/hostname
      containers:
        - name: cassandra-container
          image: {{ .Values.cassandra.image }}
          ports:
            - containerPort: 9042
              name: cql
            - containerPort: 7000
              name: intra-node
            - containerPort: 7001
              name: intra-node-tls
            - containerPort: 7199
              name: jmx
          env:
            - name: CASSANDRA_CLUSTER_NAME
              value: {{ .Values.cassandra.clusterName }}
            - name: CASSANDRA_SEEDS
              value: {{ .Values.cassandra.seeds }}
            - name: CASSANDRA_DC
              value: {{ .Values.cassandra.dc }}
            - name: CASSANDRA_RACK
              value: {{ .Values.cassandra.rack }}
            - name: MAX_HEAP_SIZE
              value: {{ .Values.cassandra.maxHeapSize }}
            - name: HEAP_NEWSIZE
              value: {{ .Values.cassandra.heapNewSize }}
            - name: TZ
              value: {{ .Values.cassandra.timezone }}
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - "nodetool status"
            initialDelaySeconds:
              {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
            successThreshold: {{ .Values.livenessProbe.successThreshold }}
          volumeMounts:
            - name: cassandra-data
              mountPath: /var/lib/cassandra
  volumeClaimTemplates:
    - metadata:
        name: cassandra-data
      spec:
        accessModes: {{ .Values.persistence.accessModes }}
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
