apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-backup-script
  namespace: default
data:
  backup.sh: |
    #!/bin/bash
    BACKUP_DIR="/backups"
    DATE=$(date +"%Y%m%d_%H%M%S")
    FILENAME="postgres_backup_$DATE.sql.gz"
    PGPASSWORD="flowinsight"

    pg_dumpall -h my-postgres-ha-postgresql-ha-postgresql-1.my-postgres-ha-postgresql-ha-postgresql-headless.default.svc.cluster.local  -U flowinsight | gzip > $BACKUP_DIR/$FILENAME

    find $BACKUP_DIR -type f -name "*.sql.gz" -mtime +7 -exec rm {} \;

    echo "Backup complete: $BACKUP_DIR/$FILENAME"
