---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cassandra-app
  namespace: default
spec:
  serviceName: cassandra-svc
  replicas: 3
  selector:
    matchLabels:
      app: cassandra-app
  template:
    metadata:
      labels:
        app: cassandra-app
    spec:
      terminationGracePeriodSeconds: 120
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - cassandra-app
                topologyKey: kubernetes.io/hostname
      containers:
        - name: cassandra-container
          image: cassandra:4.1.7
          ports:
            - containerPort: 9042
              name: cql
            - containerPort: 7000
              name: intra-node
            - containerPort: 7001
              name: intra-node-tls
            - containerPort: 7199
              name: jmx
          env:
            - name: CASSANDRA_CLUSTER_NAME
              value: "K8sCluster"
            - name: CASSANDRA_SEEDS
              value: "cassandra-0.cassandra.default.svc.cluster.local,cassandra-1.cassandra.default.svc.cluster.local,cassandra-2.cassandra.default.svc.cluster.local"
            - name: CASSANDRA_START_RPC
              value: "true"
            - name: CASSANDRA_ENDPOINT_SNITCH
              value: "GossipingPropertyFileSnitch"
            - name: CASSANDRA_DC
              value: "DC1"
            - name: CASSANDRA_RACK
              value: "Rack1"
            - name: MAX_HEAP_SIZE
              value: "512M"
            - name: HEAP_NEWSIZE
              value: "100M"
            - name: CASSANDRA_READ_REQUEST_TIMEOUT_IN_MS
              value: "5000"
            - name: CASSANDRA_WRITE_REQUEST_TIMEOUT_IN_MS
              value: "5000"
            - name: CASSANDRA_REQUEST_TIMEOUT_IN_MS
              value: "5000"
            - name: TZ
              value: "Asia/Tehran"
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - "nodetool status"
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
            successThreshold: 1
          volumeMounts:
            - name: cassandra-data
              mountPath: /var/lib/cassandra
  volumeClaimTemplates:
    - metadata:
        name: cassandra-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
