---
apiVersion: v1
kind: Service
metadata:
  name: cassandra-svc
  namespace: default
spec:
  clusterIP: None
  selector:
    app: cassandra-app
  ports:
    - name: cql
      port: 9042
    - name: intra-node
      port: 7000
    - name: intra-node-tls
      port: 7001
    - name: jmx
      port: 7199
