apiVersion: v1
kind: Service
metadata:
  name: redis-srv
  namespace: default
  labels:
    app: redis-app
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: redis-app
  ports:
    - port: 6379
      targetPort: 6379
      name: client
    - port: 16379
      targetPort: 16379
      name: gossip
