apiVersion: v1
kind: ServiceAccount
metadata:
  name: redis
  namespace: default
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: redis-app
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["configmaps", "pods"]
    verbs: ["get", "list", "patch", "update", "create"]
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: redis-app
  namespace: default
subjects:
  - kind: ServiceAccount
    name: redis
    namespace: default
roleRef:
  kind: Role
  name: redis-app
  apiGroup: rbac.authorization.k8s.io
