apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-app
  namespace: default
  labels:
    app: redis-app
spec:
  serviceName: redis-srv
  replicas: 3
  selector:
    matchLabels:
      app: redis-app
  template:
    metadata:
      labels:
        app: redis-app
    spec:
      serviceAccountName: redis
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - redis-app
                topologyKey: kubernetes.io/hostname
      containers:
        - name: redis
          image: redis:7.4-alpine
          ports:
            - containerPort: 6379
              name: client
            - containerPort: 16379
              name: gossip
            - containerPort: 8001
              name: ui
          command: ["redis-server"]
          args: ["/conf/redis.conf"]
          resources:
            requests:
              #  cpu: "1000m"
              memory: "4Gi"
            limits:
              #  cpu: "1000m"
              memory: "8Gi"
          env:
            - name: "TZ"
              value: Asia/Tehran
          volumeMounts:
            - name: conf
              mountPath: /conf
              readOnly: false
            - name: data
              mountPath: /data
              readOnly: false
          livenessProbe:
            tcpSocket:
              port: client
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 15
            periodSeconds: 10
      volumes:
        - name: conf
          configMap:
            name: redis-config
            defaultMode: 0644
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        storageClassName: local-path
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
