apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-manage-3
spec:
  selector:
    statefulset.kubernetes.io/pod-name: rabbitmq-app-1
  ports:
    - protocol: TCP
      port: 15672
      targetPort: 15672
      nodePort: 30854
  type: NodePort
